services:
  - type: web
    name: django-todo-app
    runtime: python
    rootDir: dist
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn dist.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER_EXTERNAL_HOSTNAME
        sync: false
    autoDeploy: true

databases:
  - name: django-todo-db
    databaseName: todo_db
    user: todo_user
